apiVersion: v2
name: mdm
description: A Helm chart for Kubernetes
type: application
version: 0.1.1

dependencies:
  - name: mdm-frontend
    version: "*"
    repository: "file://./charts/frontend"
    alias: frontend
  - name: mdm-backend
    version: "*"
    repository: "file://./charts/backend"
    alias: backend
