apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mdm.frontendName" . }}
  labels:
    {{- include "mdm.frontendLabels" . | nindent 4 }}
data:
  {{- with .Values.config }}
  {{ if .AIDBOX_CLIENT_ID }}AIDBOX_CLIENT_ID: {{ .AIDBOX_CLIENT_ID | b64enc }}{{ end }}
  {{ if .AIDBOX_CLIENT_SECRET }}AIDBOX_CLIENT_SECRET: {{ .AIDBOX_CLIENT_SECRET | b64enc }}{{ end }}
  {{- end }}
