apiVersion: v1
kind: Service
metadata:
  name:  {{ include "mdm.frontendName" . }}-api
  labels:
    {{- include "mdm.frontendLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: api
      port: {{ int .Values.service.apiPort }}
      protocol: TCP
      targetPort: api
  selector:
    {{- include "mdm.frontendSelectorLabels" . | nindent 4 }}
