apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "auditbox.fullname" . }}
  labels:
    {{- include "auditbox.labels" . | nindent 4 }}
data:
  BINDING: 0.0.0.0
  ELASTIC_URI: {{ required "missing config ELASTIC_URI value" .Values.config.ELASTIC_URI | quote }}
  AUDITBOX_BASE_URL: {{ required "missing config AUDITBOX_BASE_URL value" .Values.config.AUDITBOX_BASE_URL | quote }}
  IDP_AUTHORIZE_ENDPOINT: {{ required "missing config IDP_AUTHORIZE_ENDPOINT value" .Values.config.IDP_AUTHORIZE_ENDPOINT | quote }}
  IDP_TOKEN_ENDPOINT: {{ required "missing config IDP_TOKEN_ENDPOINT value" .Values.config.IDP_TOKEN_ENDPOINT | quote }}
  IDP_JWKS_URI: {{ required "missing config IDP_JWKS_URI value" .Values.config.IDP_JWKS_URI | quote }}
  AUDITBOX_LOG_LEVEL: {{ required "missing config AUDITBOX_LOG_LEVEL value" .Values.config.AUDITBOX_LOG_LEVEL | quote }}
  AUDITBOX_API_AUTH_ENABLED: {{ required "missing config AUDITBOX_API_AUTH_ENABLED value" .Values.config.AUDITBOX_API_AUTH_ENABLED | quote }}
