apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "auditbox.fullname" . }}
  labels:
    {{- include "auditbox.labels" . | nindent 4 }}
data:
  BINDING: 0.0.0.0
  ELASTIC_URI: {{ required "missing config ELASTIC_URI value" .Values.elasticUri | quote }}
