apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auditbox.fullname" . }}
  labels:
    {{- include "auditbox.labels" . | nindent 4 }}
data:
  {{- with .Values.config }}
  IDP_CLIENT_SECRET: {{ required "missing IDP_CLIENT_SECRET config value" .IDP_CLIENT_SECRET | b64enc }}
  IDP_CLIENT_ID: {{ required "missing IDP_CLIENT_ID config value" .IDP_CLIENT_ID | b64enc }}
  {{ if .AUDITBOX_ES_AUTH }}
  IDP_CLIENT_ID: {{ .AUDITBOX_ES_AUTH | b64enc }}
  {{- end }}
  {{- end }}
