apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auditbox.fullname" . }}
  labels:
    {{- include "auditbox.labels" . | nindent 4 }}
data:
  {{- with .Values.config }}
  {{ if .IDP_CLIENT_SECRET }}IDP_CLIENT_SECRET: {{ .IDP_CLIENT_SECRET | b64enc }}{{ end }}
  {{ if .IDP_CLIENT_ID }}IDP_CLIENT_ID: {{ .IDP_CLIENT_ID | b64enc }}{{ end }}
  {{- end }}
