apiVersion: v1
kind: Service
metadata:
  name: {{ include "auditbox.fullname" . }}
  labels:
    {{- include "auditbox.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: main
      protocol: TCP
      name: http
  selector:
    {{- include "auditbox.selectorLabels" . | nindent 4 }}
