{{- if .Values.auditbox.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aidbox.fullname" . }}-auditbox
  labels:
    {{- include "aidbox.labels" . | nindent 4 }}
{{- with .Values.auditbox }}
data:
  auditbox.yaml: |
    admin:
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 9901
    static_resources:
      clusters:
        - name: auditbox
          connect_timeout: 2s
          type: LOGICAL_DNS
          dns_lookup_family: V4_ONLY
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: auditbox
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: {{ .host }}
                          port_value: 443
          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              '@type': type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
              sni: {{ .host }}
        - name: auth.sd
          connect_timeout: 2s
          type: LOGICAL_DNS
          dns_lookup_family: V4_ONLY
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: auth.sd
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: {{ .auth.host }}
                          port_value: 443
          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              '@type': type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
              sni: {{ .auth.host }}
      listeners:
        - name: aidbox_listener
          address:
            socket_address:
              address: 0.0.0.0
              port_value: {{ .port }}
          filter_chains:
            - filters:
                - name: envoy.filters.network.http_connection_manager
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                    stat_prefix: ingress_http
                    access_log:
                      - name: envoy.access_loggers.stdout
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
                    http_filters:
                      - name: envoy.filters.http.credential_injector
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.credential_injector.v3.CredentialInjector
                          credential:
                            name: envoy.http.injected_credentials.oauth2
                            typed_config:
                              "@type": type.googleapis.com/envoy.extensions.http.injected_credentials.oauth2.v3.OAuth2
                              token_endpoint:
                                uri: "https://{{ .auth.host }}{{ .auth.path }}"
                                cluster: auth.sd
                                timeout: 3s
                              client_credentials:
                                client_id: {{ .auth.client | quote }}
                                client_secret:
                                  name: client-secret
                      - name: envoy.filters.http.router
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
                    route_config:
                      name: local_route
                      virtual_hosts:
                        - name: audit
                          domains: ["*"]
                          routes:
                            - match:
                                path: "/"
                              route:
                                cluster: auditbox
                                host_rewrite_literal: {{ .host }}
      secrets:
        - name: client-secret
          generic_secret:
            secret:
              environment_variable: CLIENT_SECRET
{{- end }}
{{- end }}
