{{- if and .Values.auditbox.enabled (not .Values.auditbox.auth.existingSecretName ) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aidbox.fullname" . }}-auditbox
  labels:
    {{- include "aidbox.labels" . | nindent 4 }}
data:
  secret: {{ .Values.auditbox.auth.secret | b64enc }}
{{- end }}
