apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aidbox.fullname" . }}
  labels:
    {{- include "aidbox.labels" . | nindent 4 }}
data:
  {{- with .Values.config }}
  {{ if .BOX_ADMIN_ID }}BOX_ADMIN_ID: {{ .BOX_ADMIN_ID | b64enc }}{{ end }}
  {{ if .BOX_ADMIN_PASSWORD }}BOX_ADMIN_PASSWORD: {{ .BOX_ADMIN_PASSWORD | b64enc }}{{ end }}
  {{ if .BOX_ROOT_CLIENT_ID }}BOX_ROOT_CLIENT_ID: {{ .BOX_ROOT_CLIENT_ID | b64enc }}{{ end }}
  {{ if .BOX_ROOT_CLIENT_SECRET }}BOX_ROOT_CLIENT_SECRET: {{ .BOX_ROOT_CLIENT_SECRET | b64enc }}{{ end }}
  {{ if .AIDBOX_CLUSTER_SECRET }}AIDBOX_CLUSTER_SECRET: {{ .AIDBOX_CLUSTER_SECRET | b64enc }}{{ end }}
  {{ if .AIDBOX_SUPERUSER }}AIDBOX_SUPERUSER: {{ .AIDBOX_SUPERUSER | b64enc }}{{ end }}
  {{ if .BOX_OBSERVABILITY_ELASTIC_SEARCH_AUTH }}BOX_OBSERVABILITY_ELASTIC_SEARCH_AUTH: {{ .BOX_OBSERVABILITY_ELASTIC_SEARCH_AUTH | b64enc }}{{ end }}
  {{ if .AIDBOX_LICENSE }}AIDBOX_LICENSE: {{ .AIDBOX_LICENSE | b64enc }}{{ end }}
  {{ if .BOX_DB_USER }}BOX_DB_USER: {{ .BOX_DB_USER | b64enc }}{{ end }}
  {{ if .BOX_DB_PASSWORD }}BOX_DB_PASSWORD: {{ .BOX_DB_PASSWORD | b64enc }}{{ end }}
  {{- end }}
