apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mpi.fullname" . }}
  labels:
    {{- include "mpi.labels" . | nindent 4 }}
data:
  {{- with .Values.config }}
  {{ if .AIDBOX_CLIENT_ID }}AIDBOX_CLIENT_ID: {{ .AIDBOX_CLIENT_ID | b64enc }}{{ end }}
  {{ if .AIDBOX_CLIENT_SECRET }}AIDBOX_CLIENT_SECRET: {{ .AIDBOX_CLIENT_SECRET | b64enc }}{{ end }}
  {{ if .PGUSER }}PGUSER: {{ .PGUSER | b64enc }}{{ end }}
  {{ if .PGPASSWORD }}PGPASSWORD: {{ .PGPASSWORD | b64enc }}{{ end }}
  {{- end }}
