apiVersion: v1
kind: Service
metadata:
  name: {{ include "mpi.fullname" . }}-api
  labels:
    {{- include "mpi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: api
      port: {{ int .Values.service.apiPort }}
      protocol: TCP
      targetPort: api
  selector:
    {{- include "mpi.selectorLabels" . | nindent 4 }}
