apiVersion: v1
kind: Service
metadata:
  name: {{ include "mpi.fullname" . }}-metrics
  labels:
    {{- include "mpi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: metrics
      port: {{ int .Values.service.metricsPort }}
      protocol: TCP
      targetPort: metrics
  selector:
    {{- include "mpi.selectorLabels" . | nindent 4 }}
