apiVersion: v1
kind: Service
metadata:
  name: {{ include "mdm.backendName" . }}-metrics
  labels:
    {{- include "mdm.backendLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: metrics
      port: {{ int .Values.service.metricsPort }}
      protocol: TCP
      targetPort: metrics
  selector:
    {{- include "mdm.backendSelectorLabels" . | nindent 4 }}
