apiVersion: v1
kind: Service
metadata:
  name: {{ include "mdm.backendName" . }}-api
  labels:
    {{- include "mdm.backendLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: api
      port: {{ int .Values.service.apiPort }}
      protocol: TCP
      targetPort: api
  selector:
    {{- include "mdm.backendSelectorLabels" . | nindent 4 }}
