protocol: http

replicaCount: 1

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  name: ""

podAnnotations: {}
deploymentAnnotations: {}
podLabels: {}
podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  requests:
    cpu: 500m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /api/health
    port: api
  periodSeconds: 10
  failureThreshold: 10
readinessProbe:
  httpGet:
    path: /api/health
    port: api
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 5
startupProbe:
  httpGet:
    path: /api/health
    port: api
  initialDelaySeconds: 20
  periodSeconds:  5
  failureThreshold: 10

# This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

updateStrategy:
  type: RollingUpdate

nodeSelector: {}

tolerations: []

affinity: {}

extraEnvFromConfigMaps: []
extraEnvFromSecrets: []

serviceMonitor:
  enabled: false
